name: Scraper BRZ - XML Autom谩tico

on:
  schedule:
    # Roda todos os dias s 06:00 e 18:00 (Hor谩rio de Bras铆lia)
    # No servidor UTC 茅 +3h, ent茫o configuramos 09:00 e 21:00 UTC
    - cron: '0 9,21 * * *'
  workflow_dispatch: # Permite rodar manualmente clicando no bot茫o

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Baixar c贸digo do reposit贸rio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar depend锚ncias
        run: npm install

      - name:  Rodar Rob么 (Extrair Dados)
        run: node index.js
        # Isso vai gerar o brz_imoveis.json

      - name:  Rodar Conversor (Gerar XML)
        run: node conversor.js
        # Isso vai gerar o brz_imoveis_wp.xml

      - name:  Salvar XML no Reposit贸rio
        run: |
          git config --global user.name "Robo BRZ"
          git config --global user.email "robo@brz.com"
          git add brz_imoveis_wp.xml
          # S贸 commita se houver mudan莽as para evitar erro
          git diff --quiet && git diff --staged --quiet || (git commit -m "Atualizacao automatica: Imoveis BRZ" && git push)